name: Lint
on:
  pull_request:
    branches: [main]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v22
        uses: actions/setup-node@v1
        with:
          node-version: 22
      - name: npm ci --omit=dev
        run: npm ci --omit=dev
      - name: eslint
        uses: icrawl/action-eslint@v1
        with:
          custom-glob: "**/*.{ts,tsx}"
